project:
  type: default
  output-dir: docs
  render:
    - index.qmd
    - dice/index.qmd
    - llm/index.qmd
  resources:
    - styles.css
    - llm/voting.csv
    - dice/dice-fallback.R
    - llm/llm-fallback.R

format:
  live-html:
    toc: true
    toc-depth: 2
    theme: cosmo
    smooth-scroll: true
    code-tools: false

engine: knitr

live:
  show-hints: true
  show-solutions: true
